services:
  postgres_dealership_db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      POSTGRES_DB: $POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    #although the current .env file does not contain DB_Host, DB_PORT etc. even though db.js requires it
    #we are currently setting those variable manully in here and mapping them to the current values in our .env
    #hence why we are mapping DB_USER to POSTGRESDB_USER
    environment:
      #since the database is no longer being hosted on the local machine and inside the dockert container, the service 'pg_container' become this new db host
      DB_HOST: postgres_dealership_db
      DB_USER: $POSTGRESDB_USER
      DB_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      DB_NAME: $POSTGRESDB_DATABASE
      DB_PORT: $POSTGRESDB_DOCKER_PORT
    depends_on:
      - postgres_dealership_db

volumes:
  postgres-data:
